import { Link } from 'react-router-dom';
import './Home.css';

function Home() {
  return (
    <div className="home-container">
      <h1 className="home-title">TruePic</h1>
      <p className="home-description">
        Upload an image and we'll tell you whether it was created by a human or generated by AI — instantly.
      </p>

      <div className="home-preview-box">
        <p>See how it works:</p>
        <img
          src="/sample-result.png"
          alt="Sample Result"
          className="home-sample-image"
        />
      </div>

      <Link to="/app">
        <button className="home-try-button">Try It Now</button>
      </Link>
    </div>
  );
}

export default Home;
